### ISSUE TITLE
Fractals Overlay disappeared

### ISSUE THREAD

**Issue by jschwarzwalder** [a727891/BlishHud-Raid-Clears#19]
Over the weekend when I logged in I didn't have the table for the Fractals anymore. I could click on the Clears Tracker Icon and it was toggling seeing the Strikes. I turned the opacity to 100% in the settings and didn't see a box for where the Fractals would display. 

I tried disabling and enabling the module but it didn't fix the problem. I tried removing the module and reinstalling and it didn't fix the problem. I tried making Raids and Dungeons visible by checking the XX hide/show on menubar icon click, as well as checking the box to Show XX overlay. I couldn't see Raids, Dungeons, or Fractals.

I exited BlishHud and edited the Settings.json file to delete the RaidingClears section and removed the module from BlishHud UI then was able to reinstall with factory defaults and see the Fractals and Strikes (as well as Raids and Dungeons)

My guess is that somehow the Fractals overlay (and Raid Overlay) got moved off my screen somehow and since I couldn't see it I couldn't grab it to move it back. 

A feature to lock the overlay in place on my screen might prevent it from happening in the future as well. 

It would be great if there was a way to either reset the position of the overlay, or to remove the data about the module when I delete Module.

**Comment by a727891** [comment]
Thank you for reaching out with this feedback!

I saw three main points in your comment,

### Lock the overlay positions

Leaving the windows unlocked and movable is definitely not how I envisioned the module getting used.
Once you are happy with where the windows appear, you can uncheck this box and they will no longer respond to mouse drag events. This setting is independent for all four window sections(raids, strikes, fractals, dungeons)
Unchecking the "mouse hover tooltips" as well will make the window ignore the mouse completely.
![image](https://github.com/a727891/BlishHud-Raid-Clears/assets/2788304/b47fb1f1-ca7e-4409-abf8-3b29a3f253b3)

### Resetting configuration

This is a native option in Blish itself. The gear icon next to enable module has a clear settings option when the module is not loaded.
![image](https://github.com/a727891/BlishHud-Raid-Clears/assets/2788304/c6256aff-20e2-496d-bd9c-bae46fd43725)

### Windows lost off screen

I added a **new setting in version 2.6.1** that clamps the windows to the screen bounds. When ever that option is (re)enabled (click off click on) it will teleport the windows back to the screen bounds as well. Moving the windows with it enabled will teleport them to the screen edge on mouse drag release if they are leaving the viewport. This will default to ON for all users.
![image](https://github.com/a727891/BlishHud-Raid-Clears/assets/2788304/735c0113-7db0-4db1-b44b-dd3ddf87240b)
